config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get "informacion_agronomica/fenologia", to: "agronomic_information#phenoilogy", as: :phenoilogy
  get "informacion_agronomica/cobertura", to: "agronomic_information#cover", as: :cover

  get "granos_basicos", to: "basic_grains#index", as: :basic_grains
  get "granos_basicos/get_images", to: "basic_grains#get_images", as: :basic_grains_get_images

  get "corredor_seco", to: "ca_dry_corridor#index", as: :ca_dry_corridor
  get "corredor_seco/get_images", to: "ca_dry_corridor#get_images", as: :ca_dry_corridor_get_images

  get "estado_de_la_vegetacion", to: "state_of_vegetation#index", as: :state_of_vegetation
  get "estado_de_la_vegetacion/get_images", to: "state_of_vegetation#get_images", as: :state_of_vegetation_get_images
  
  get "referencias", to: "references#index", as: :references
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    enum main_class: {
        asi: 'AS', sequia: 'MR', probabilidad: 'PE'
    }

    enum period_type: {
        t: 't', y: 'y'
    }

    enum crop_type: {
        rice: 1, corn_beans: 2, perennial_crops: 3, shrub_vegetation: 4
    }

    enum sowing_type: {
        s1: 's1', s2: 's2'
    }

    enum pixel_type: {
        m: 'M', n: 'N'
    }

    scope :as_y, lambda { where(main_class: :asi, period_type: 'y')}
    scope :as_t, lambda { where(main_class: :asi, period_type: 't')}

    scope :mr_y, lambda { where(main_class: :sequia, period_type: 'y')}
    scope :mr_t, lambda { where(main_class: :sequia, period_type: 't')}

    scope :pe_y, lambda { where(main_class: :probabilidad, period_type: 'y')}
    
end

app/controllers/agronomic_information_controller.rb
class AgronomicInformationController < ApplicationController
    def crops
    end 

    def phenoilogy
    end
	
	def cover
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/basic_grains_controller.rb
class BasicGrainsController < ApplicationController

    def index 
        @grains_images = ImagesFormModel.new
    end

    def get_images
        @grains_images = ImagesFormModel.new(grain_search_params)
        @images = ImagesSearchService.call(@grains_images)

        respond_to do |format|
            format.html { render :layout => false }
          end
    end

    private 

    def grain_search_params
        params.require(:grains_images_form).permit(:main_class, :percentage, :period_type, :crop_type, :is_csc, :is_dif, :page)
    end
end

app/controllers/ca_dry_corridor_controller.rb
class CaDryCorridorController < ApplicationController
    def index 
        @images = ImagesFormModel.new
    end

    def get_images
        @images = ImagesFormModel.new(grain_search_params)
        @images = ImagesSearchService.call(@images)

        respond_to do |format|
            format.html { render :layout => false }
          end
    end

    private 

    def grain_search_params
        params.require(:ca_dry_corridor_images_form).permit(:main_class, :percentage, :crop_type, :period_type, :is_csc, :is_dif, :page)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @files = LoadLastImagesService.call.map{|img| img.full_path}
  end

  def inf_agronoma
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
	def	index
	end
end

app/controllers/state_of_vegetation_controller.rb
class StateOfVegetationController < ApplicationController
    def index 
        @images = ImagesFormModel.new
    end

    def get_images
        @images = ImagesFormModel.new(state_of_vegetation_params)
        @images = ImagesSearchService.call(@images)

        respond_to do |format|
            format.html { render :layout => false }
          end
    end

    private 

    def state_of_vegetation_params
        params.require(:state_of_vegetation_images_form).permit(:year, :dd, :is_dif, :page)
    end
end

app/helpers/agronomic_information_helper.rb
module AgronomicInformationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_grains_helper.rb
module BasicGrainsHelper
    def get_index_type(index)
        case index 
            when 'asi'
                "Índice de estrés agrícola (ASI)"
            when 'sequia'
                "Categoría de sequía"
            when 'probabilidad'
                "Probabilidad histórica de sequía"
        end
    end

    def get_crop_type(crop, is_csc)
        case crop 
            when 'rice'
                is_csc ? "Cultivos anuales" : "Arroz"
            when 'corn_beans'
                is_csc ? "Pastos" : "Maíz/Frijoles"
            when 'perennial_crops'
                "Cultivos Perennes"
            when 'shrub_vegetation'
                "Vegetación Arbustiva"
        end
    end

    def get_sowing_type(sowing)
        case sowing 
            when 's1'
                "Primera"
            when 's2'
                "Postrera"
        end
    end

    def get_period_type(period)
        case period 
            when 't'
                "Decadía (10 días)"
            when 'y'
                "Año"
        end
    end
end

app/helpers/ca_dry_corridor_helper.rb
module CaDryCorridorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/state_of_vegetation_helper.rb
module StateOfVegetationHelper

    def get_vegetation_type(veg_type)
        case veg_type 
            when 'rice'
                "Estado de la vegetación"
            when 'corn_beans'
                "Estado de la vegetación por área administrativa"
        end
    end
end

app/helpers/vsa_helper.rb
module VsaHelper
end

app/views/agronomic_information/cover.html.erb
<div class="jumbotron">
<h1>Cultivos y otras coberturas de la tierra</h1>
&nbsp;
	<div class="row mb-2">
		<div class="col-md-6">
			<strong>Granos básicos en Centroamérica</strong>
			&nbsp;
			<a href="<%= image_path("Centroamerica_clases.png") %>"><img src="<%= image_path("Centroamerica_clases.png") %>" width="100%" /></a>
		</div>
		<div class="col-md-6">
			<strong>Cobertura de la tierra en el Corredor Seco Centroamericano</strong>
			&nbsp;
			<a href="<%= image_path("Centroamerica_CSC_clases.png") %>"><img src="<%= image_path("Centroamerica_CSC_clases.png") %>"  width="100%" /></a>
		</div>
	</div>
</div>

app/views/agronomic_information/crops.erb
<div class="jumbotron">
  <div class="container">
    <p><strong>Sistema mundial de información y alerta sobre la alimentación y la agricultura (SMIA)</strong> supervisa el estado de los principales cultivos alimentarios en 
    todo el mundo para evaluar las perspectivas de producción. Para fundamentar el análisis y complementar la información de campo, el SMIA utiliza datos teledetectados que 
    pueden proporcionar información valiosa sobre la disponibilidad del agua y la salud de la vegetación durante los periodos vegetativos. Además de las estimaciones de 
    precipitación y el índice Normalizado Diferencial de la Vegetación (NDVI, por sus siglas en inglés), el SMIA y la División CBC de la FAo han desarrollado el Índice
    de Estrés Agrícola (ASI, por sus siglas en inglés), un indicador rápido para la identificación temprana de zonas agrícolas probablemente afectadas por episodios de sequía,
    o por sequía en casos extremos.
    </p>
  </div>
</div>
<div class="d-flex flex-row-reverse">
    <span>Últimos datos: <strong>década 1 jun 2018<strong></span>
</div>

<div class"row">
    <h1>Global</h1>
    <div class="col-12">
        <div class="card">
            <div class="card-body row">
                <div class="col-md-8 text-center">
                    <a href="<%= image_path("Centroamerica_CSC_clases.png") %>" 
                    data-lightbox="image-1" 
                    data-title="Sistema de vigilancia de la sequia agrícola en Centroamerica">
                        <img src="<%= image_path("Centroamerica_CSC_clases_500_647.png") %>">
                    </a>
                </div>
                <div class="col-md-4">
                    <div class="nav flex-column nav-pills" id="left-nav" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Información agronómica</a>
                        <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Estado de la vegetación</a>
                        <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Granos básicos</a>
                        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Corredor Seco Centroamericano</a>
                        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Referencias</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/agronomic_information/phenoilogy.html.erb
<div class="jumbotron">
	<header>
		<h1>Fenología</h1>
		<p><strong>El progreso de cultivo</strong> representa el desarrollo del periodo vegetativo del cultivo expresado en porcentaje. Para cualquier periodo de diez días del año, el mapa indica cuánto ha avanzado la campaña agrícola, representando dicho avance con un valor entre el 0 y el 100 por ciento (es decir, 50 por ciento es el punto medio del periodo vegetativo). El avance de la campaña agrícola se basa en el promedio de la serie histórica de la fenología de la vegetación para cada píxel. Esta simplificación supone que la fenología de los cultivos es estática y, por tanto, que los periodos vegetativos avanzan a un ritmo constante cada año.</p>
	</header>
	<h2>Campaña 1</h2>
	<h3>Granos básicos</h3>
	<div class="row mb-2">
	
		<div class="col-md-6">
				<a href="<%= image_path("Centroamerica_SOS1.png") %>"><img src="<%= image_path("Centroamerica_SOS1.png") %>" width="100%" /></a>
		</div>
		<div class="col-md-6">
				<a href="<%= image_path("Centroamerica_EOS1.png") %>"><img src="<%= image_path("Centroamerica_EOS1.png") %>" width="100%" /></a>
		</div>
		
		
	</div>
	&nbsp;
	
	<h3>Corredor seco</h3>
	<div class="row mb-2">
	
		<div class="col-md-6">
				<a href="<%= image_path("Centroamerica_CSC_SOS1.png") %>"><img src="<%= image_path("Centroamerica_CSC_SOS1.png") %>" width="100%" /></a>
		</div>
		<div class="col-md-6">
				<a href="<%= image_path("Centroamerica_CSC_EOS1.png") %>"><img src="<%= image_path("Centroamerica_CSC_EOS1.png") %>" width="100%" /></a>
		</div>
		
		
	</div>
	
	<h2>Campaña 2</h2>
	<h3>Granos básicos</h3>
	<div class="row mb-2">
	
		<div class="col-md-6">
				<a href="<%= image_path("Centroamerica_SOS2.png") %>"><img src="<%= image_path("Centroamerica_SOS2.png") %>" width="100%" /></a>
		</div>
		<div class="col-md-6">
				<a href="<%= image_path("Centroamerica_EOS2.png") %>"><img src="<%= image_path("Centroamerica_EOS2.png") %>" width="100%" /></a>
		</div>
		
		
	</div>
	
	&nbsp;
	
	<h3>Corredor seco</h3>
	<div class="row mb-2">
	
		<div class="col-md-6">
				<a href="<%= image_path("Centroamerica_CSC_SOS2.png") %>"><img src="<%= image_path("Centroamerica_CSC_SOS2.png") %>" width="100%" /></a>
		</div>
		<div class="col-md-6">
				<a href="<%= image_path("Centroamerica_CSC_EOS2.png") %>"><img src="<%= image_path("Centroamerica_CSC_EOS2.png") %>" width="100%" /></a>
		</div>
		
		
	</div>
</div>

app/views/basic_grains/get_images.html.erb
<div class="card-deck">
  <% @images.each_with_index do |img, index| %>
    <%= render "shared/image", img: img, index: index, is_csc: false %>
  <%end%>
</div>

<div class="row">
    <div class="col-12">
        <%= paginate @images, :remote => true, param_name: "grains_images_form[page]", theme: 'twitter-bootstrap-4' %>
    </div>
</div>

app/views/basic_grains/index.html.erb
<%= content_for :embed_js do %>
  <script>
    $(document).on('turbolinks:load', function(){
        BASIC_GRAINS.init();
    });
  </script>
<% end %>

<div class="jumbotron">
  <div class="container">
    <%= form_with(url: basic_grains_get_images_path, model: @grains_images, method: :get) do |f| %>
        <div class="row">
            <h1>Granos Básicos de Centro América</h1>
            <input type="hidden" name="grains_images_form[is_csc]" value="0">
            <input type="hidden" name="grains_images_form[is_dif]" value="0">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="main_class">Índices</label>
                    <select class="form-control" id="main_class" name="grains_images_form[main_class]">
                        <option value="asi">Índice de estrés agrícola (ASI)</option>
                        <option value="sequia">Categorías de Sequía</option>
                        <option value="probabilidad">Probabilidad Histórica de Sequía</option>
                    </select>
                </div>
                <div class="form-group" id="periodSelect">
                    <label for="period_type">Periodo</label>
                    <select class="form-control" id="period_type" name="grains_images_form[period_type]">
                        <option value="t">Decadías (10 días)</option>
                        <option value="y">Año</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="crop_type">Tipo de cultivos</label>
                    <select class="form-control" id="crop_type" name="grains_images_form[crop_type]">
                        <option value="rice">Arroz</option>
                        <option value="corn_beans">Maíz/Frijoles</option>
                    </select>
                </div>
                <div class="form-group" id="percentage-container" style="<%= @grains_images.percentage == 'porcentage' ? '' : 'display:none;' %>">
                    <label for="percentage">Probabilidad histórica de sequía</label>
                    <select class="form-control" id="percentage" name="grains_images_form[percentage]">
                        <option value="20">20%</option>
                        <option value="30">30%</option>
                        <option value="50">50%</option>
                    </select>
                </div>                
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
            <div class="col-md-6">

            </div>
        </div>
    <%end%>
  </div>
</div>
<div class="row">
    <div class="col-12" id="container">
    </div>
</div>

app/views/ca_dry_corridor/get_images.html.erb
<div class="card-deck">
  <% @images.each_with_index do |img, index| %>
    <%= render "shared/image", img: img, index: index, is_csc: true %>
  <%end%>
</div>

<div class="row">
    <div class="col-12">
        <%= paginate @images, :remote => true, param_name: "ca_dry_corridor_images_form[page]", theme: 'twitter-bootstrap-4' %>
    </div>
</div>

app/views/ca_dry_corridor/index.html.erb
<%= content_for :embed_js do %>
  <script>
    $(document).on('turbolinks:load', function(){
        BASIC_GRAINS.init();
    });
  </script>
<% end %>

<div class="jumbotron">
  <div class="container">
    <%= form_with(url: ca_dry_corridor_get_images_path, model: @images, method: :get) do |f| %>
        <div class="row">
            <h1>Corredor Seco Centroamericano</h1>
			&nbsp;
			<input type="hidden" name="ca_dry_corridor_images_form[is_csc]" value="1">
            <input type="hidden" name="ca_dry_corridor_images_form[is_dif]" value="0">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="main_class">Índices</label>
                    <select class="form-control" id="main_class" name="ca_dry_corridor_images_form[main_class]">
                        <option value="asi">Índice de estrés agrícola (ASI)</option>
                        <option value="sequia">Categorías de Sequía</option>
                        <option value="probabilidad">Probabilidad Histórica de Sequía</option>
                    </select>
                </div>
                <div class="form-group" id="periodSelect">
                    <label for="period_type">Periodo</label>
                    <select class="form-control" id="period_type" name="ca_dry_corridor_images_form[period_type]">
                        <option value="t">Decadías (10 días)</option>
                        <option value="y">Año</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="crop_type">Cobertura</label>
                    <select class="form-control" id="crop_type" name="ca_dry_corridor_images_form[crop_type]">
                        <option value="rice">Cultivos anuales</option>
                        <option value="corn_beans">Pastos</option>
                        <option value="perennial_crops">Cultivos Perennes</option>
                        <option value="shrub_vegetation">Vegetación Arbustiva</option>
                    </select>
                </div>
                <div class="form-group" id="percentage-container" style="<%= @images.percentage == 'porcentage' ? '' : 'display:none;' %>">
                    <label for="percentage">Probabilidad histórica de sequía</label>
                    <select class="form-control" id="percentage" name="ca_dry_corridor_images_form[percentage]">
                        <option value="20">20%</option>
                        <option value="30">30%</option>
                        <option value="50">50%</option>
                    </select>
                </div>                
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
            <div class="col-md-6">

            </div>
        </div>
    <%end%>
  </div>
</div>
<div class="row">
    <div class="col-12" id="container">
    </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <p style="text-align:justify"><img src="<%= image_path("crops.jpg")%>" height="400px" style="float: right; margin-left: 20px" /><strong>El sistema de vigilancia de la sequía agrícola</strong> se establece con la colaboración de la Organización para la Agricultura y 
	la Alimentación de las Naciones Unidas (FAO) para el fortalecimiento de las capacidades nacionales y regionales para el monitoreo y alerta 
	temprana de la sequía en agricultura con el uso de información geoespacial.  El sistema sirve de apoyo a la adaptación al cambio climático y
	gestión de riesgos.  Este esfuerzo a la vez complementa las actividades que el Comité Regional de Recursos Hidráulicos (CRRH) realiza con la 
	“Perspectiva Regional del Clima”.  El Sistema Mundial de Información y Alerta sobre la alimentación y la agricultura (SMIA) contribuye a las 
	regiones y países suministrando las imágenes en tiempo cuasi-real (cada 10 días) para el cálculo del Índice de Estrés Agrícola (ASI, por sus 
	siglas en inglés), un indicador rápido para la identificación temprana de zonas agrícolas con alta probabilidad de ser afectadas por episodios 
	de sequía, o por sequía extremas.</p>
    <p>ASIS en el 2016 obtuvo el premio por el uso de la información geoespacial en agricultura: <strong>Geospatial World Excellence Award.</strong> 
  </div>
</div>
<div class="d-flex flex-row-reverse">
    <span>Últimos datos: <strong>década 1 jun 2018<strong></span>
</div>

<div class"row">
    <div class="col-12">
        <div class="card">
            <div class="card-body row">
                <div class="col-md-12 text-center">
                    <div id="imageCarouselHomeIndex" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <% @files.each_with_index do |f, index| %>
                                <li data-target="#imageCarouselHomeIndex" data-slide-to="<%= index %>" class="<%= index == 0 ? "active" : '' %>"></li>
                            <%end%>
                        </ol>
                        <div class="carousel-inner">
                            <% @files.each_with_index do |f, index| %>
                                <div class="carousel-item <%= index == 0 ? "active" : '' %>">
                                    <img class="d-block w-100" src="<%= f %>">
                                </div>
                            <%end%>
                        </div>
                        <a class="carousel-control-prev" href="#imageCarouselHomeIndex" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Anterior</span>
                        </a>
                        <a class="carousel-control-next" href="#imageCarouselHomeIndex" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Siguiente</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>VigilanciaSequiaAgricola</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	
	<% if Rails.env.production? %>
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-73691458-1', 'auto');
    </script>
<% end %>

  </head>

  <body>
    <%= render "shared/nav" %>
    <main class="container-fluid">
      <%= yield %>
    </main>
    <% if content_for?(:embed_js) %>
      <%= yield :embed_js %>
    <%end%>
  </body>

</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="http://asis.centroclima.org/"><img src="<%= image_path("crrh.png") %>" height="42" /></a>
  <a class="navbar-brand" href="http://asis.centroclima.org/"><img src="<%= image_path("fao.png") %>" height="42" /></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">Inicio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link dropdown-toggle" href="#" id="informacionAgronoma" data-toggle="dropdown" 
        aria-haspopup="true" aria-expanded="false">Información agronómica</a>
        <div class="dropdown-menu" aria-labelledby="informacionAgronoma">
          <a class="dropdown-item" href="<%= cover_path %>">Cultivos y otras coberturas de la tierra</a>
          <a class="dropdown-item" href="<%= phenoilogy_path %>">Fenología</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= state_of_vegetation_path %>">Estado de la vegetación</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" href="<%= basic_grains_path %>" id="branosBasicos">Granos básicos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= ca_dry_corridor_path %>" id="corredorSeco">Corredor Seco</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="<%= references_path %>" id="reference">Referencias</a>
      </li>
    </ul>
  </div>
</nav>

app/views/state_of_vegetation/index.html.erb
<%= content_for :embed_js do %>
  <script>
    $(document).on('turbolinks:load', function(){
        BASIC_GRAINS.init();
    });
  </script>
<% end %>

<div class="jumbotron">
  <div class="container">
    <%= form_with(url: state_of_vegetation_get_images_path, model: @images, method: :get) do |f| %>
        <div class="row">
            <h1>Estado de la vegetación</h1>
			<p tyle="text-align:justify"><strong>El Índice de Salud de la Vegetación (VHI, por sus siglas en inglés) o estado de la vegetación</strong>; es un 
			índice compuesto y el indicador elemental utilizado para calcular el ASI. Combina tanto el VCI como el Índice de Condiciones de Temperatura
			(TCI, por sus siglas en inglés). El TCI se calcula utilizando una ecuación similar a la del VCI, pero relaciona la temperatura actual con 
			el máximo a largo plazo, ya que se supone que las temperaturas más altas tienden a deteriorar las condiciones de la vegetación. Una 
			disminución del VHI tras, por ejemplo, una reducción del VCI (vegetación verde relativamente deficiente) y un TCI creciente (temperaturas 
			más cálidas) sería sinónimo de vegetación estresada, y durante un período más largo, un indicativo de sequía. A los componentes del VHI (
			VCI y TCI) se les otorga la misma ponderación cuando se calcula el índice.</p>
			&nbsp;
			<input type="hidden" name="state_of_vegetation_images_form[is_csc]" value="0">
            <input type="hidden" name="state_of_vegetation_images_form[is_dif]" value="1">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="year">Índices</label>
                    <select class="form-control" id="year" name="state_of_vegetation_images_form[year]">
                        <%= (1984..DateTime.now.year).to_a.reverse.each do |year| %>
                            <option value="<%= year %>"><%= year %></option>
                        <%end%>
                    </select>
                </div>
                <div class="form-group" id="periodSelect">
                    <label for="dd">Deca día</label>
                    <select class="form-control" id="dd" name="state_of_vegetation_images_form[dd]">
                        <option value="01-01">1 ene</option>
                        <option value="01-11">2 ene</option>
                        <option value="01-21">3 ene</option>
                        <option value="02-01">1 feb</option>
                        <option value="02-11">2 feb</option>
                        <option value="02-21">3 feb</option>
                        <option value="03-01">1 mar</option>
                        <option value="03-11">2 mar</option>
                        <option value="03-21">3 mar</option>
                        <option value="04-01">1 abr</option>
                        <option value="04-11">2 abr</option>
                        <option value="04-21">3 abr</option>
                        <option value="05-01">1 may</option>
                        <option value="05-11">2 may</option>
                        <option value="05-21">3 may</option>
                        <option value="06-01">1 jun</option>
                        <option value="06-11">2 jun</option>
                        <option value="06-21">3 jun</option>
                        <option value="07-01">1 jul</option>
                        <option value="07-11">2 jul</option>
                        <option value="07-21">3 jul</option>
                        <option value="08-01">1 ago</option>
                        <option value="08-11">2 ago</option>
                        <option value="08-21">3 ago</option>
                        <option value="09-01">1 sep</option>
                        <option value="09-11">2 sep</option>
                        <option value="09-21">3 sep</option>
                        <option value="10-01">1 oct</option>
                        <option value="10-11">2 oct</option>
                        <option value="10-21">3 oct</option>
                        <option value="11-01">1 nov</option>
                        <option value="11-11">2 nov</option>
                        <option value="11-21">3 nov</option>
                        <option value="12-01">1 dic</option>
                        <option value="12-11">2 dic</option>
                        <option value="12-21">3 dic</option>
                    </select>
                </div>        
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
            <div class="col-md-6">

            </div>
        </div>
    <%end%>
  </div>
</div>
<div class="row">
    <div class="col-12" id="container">
    </div>
</div>